function G_data = get_bf_graded_grid(G_data, C_wl_bf, k, Lgrad_coeff, ...
    alpha)
% In this function we will compute the information for the basis function
% grid given the inputs.

[G_data.x_1_col, G_data.y_1_col, G_data.x_2_col, G_data.y_2_col,...
    G_data.t_bf_grid, G_data.t_mid_col, ~, ~, G_data.L] =...
    discretistion_vars_graded(G_data.G, C_wl_bf, k, Lgrad_coeff, alpha);
