function G_data = get_graded_quad_points(G_data, C_wl_quad, k, ...
    Lgrad_coeff, alpha)
% In this function we compute the graded quadrature points

[G_data.x_1_q, G_data.y_1_q, G_data.x_2_q, G_data.y_2_q, ...
    G_data.t_grid, G_data.t_mid_q, G_data.w, G_data.N, G_data.L] = ...
    discretistion_vars_graded(G_data.G, C_wl_quad, k, Lgrad_coeff, alpha);
